### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by RaphaelMarinier** [wichtounet/swr-calculator#7]
Hi all,

Thanks for this interesting project.
As far as I can see, there is no license attached to the code, which means that this is effectively proprietary code which cannot be modified, re-used, etc.
Could a license be added? For instance, an MIT or Apache v2 license would be among the most permissive.

Thanks.

**Comment by thepoorswiss** [comment]
HI @RaphaelMarinier 

Excellent point. All my code is usually on MIT license, so I have put MIT as well on this repo 👍
